### ISSUE TITLE
Error bundling this project

### ISSUE THREAD

**Issue by calbertts** [guybedford/jspm-react-component-demo#5]
I've executed `jspm bundle test.js -wid` in the root of this project after install the dependencies, but I'm getting this error:

```
err  Error on translate for test.js at file:///Users/Projects/jspm-react-component-demo/test.js
  Error: Unable to calculate canonical name to bundle /Users/npm/lib/node_modules/jspm/node_modules/babel-runtime/. Ensure that this module sits within the baseURL or a wildcard path config.
      at getCanonicalNamePlain (/Users/npm/lib/node_modules/jspm/node_modules/systemjs-builder/lib/utils.js:218:13)
      at getCanonicalName (/Users/npm/lib/node_modules/jspm/node_modules/systemjs-builder/lib/utils.js:145:19)
      at Object.<anonymous> (/Users/Projects/jspm-react-component-demo/jspm_packages/npm/systemjs-plugin-babel@0.0.5/plugin-babel.js:25:29)
      at /Users/Projects/jspm-react-component-demo/jspm_packages/npm/systemjs-plugin-babel@0.0.5/plugin-babel.js:186:4
      at /Users/Projects/jspm-react-component-demo/jspm_packages/npm/systemjs-plugin-babel@0.0.5/plugin-babel.js:187:3
      at Object.exports.runInThisContext (vm.js:54:17)
  Evaluating /Users/Projects/jspm-react-component-demo/jspm_packages/npm/systemjs-plugin-babel@0.0.5/plugin-babel.js
  Error loading /Users/Projects/jspm-react-component-demo/jspm_packages/npm/systemjs-plugin-babel@0.0.5/plugin-babel.js
```

**Comment by guybedford** [comment]
Try upgrading the Babel plugin with `jspm install plugin-babel`. It's tricky to try and keep all the dependencies in all these demo projects up to date!

**Comment by dan-teitsort** [comment]
The suggestion worked for me:
`jspm install plugin-babel`

**Comment by tonyeung** [comment]
I'm not sure if i should be opening a new issue for this or do a PR or w/e. The HMR packages are out of date. Maybe I missed a step or something, but the hello world page would not update when I change it component.js until i updated chokidar and hot-reloading packages

**Comment by guybedford** [comment]
It's difficult to keep demos always up-to-date. PRs with necessary updates are always welcome.
